# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-scholar
  - jekyll-smartify
  - jekyll-mentions

jekyll-mentions:
  base_url: https://twitter.com

markdown: kramdown
highlighter: rouge

# Site settings
title: "CSCL"
description: > # this means to ignore newlines until "email:"


email: hello@cscl.co
#blog logo
logo: "cscl.co/assets/images/cscl_logo.png"
# blog cover
cover: "cscl.co/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'S.F.'
author: 'S.F.'
author_image: "/assets/images/author.jpg"

paginate:	6
paginate_path: "/blog/page:num"
# permalink: /:categories/:year/:month/:day/:title 

url: "https://solenfeyissa.github.io/cscl.co/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@ssolen'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/ssolen
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#    icon:	github
#    url:	https://github.com/solenfeyissa
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

  - icon: rss
    url:  https://cscl-co.github.io/cscl/feed.xml
    desc: Subscribe
    share_url:
    share_title:
    share_link:

  - icon: envelope
    url:  mailto:hello@cscl.co
    desc: Email
    share_url:
    share_title:
    share_link:   

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
